name: Tests By Symfony Version

on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
      - 0.*
      - 1.*
  schedule:
    # Weekly on Mondays at 3pm UTC
    - cron:  '0 15 * * 1'

jobs:
  symfony62:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1
    with:
      phpUnitVersion: 9.5
      symfony: 6.2
      
  symfony63:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1
    with:
      phpUnitVersion: 9.5
      symfony: 6.3
