name: Tests By Symfony Version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
      - 0.*
      - 1.*
  schedule:
    # Weekly on Mondays at 3pm UTC
    - cron:  '0 15 * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    timeout-minutes: 15
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.0 ]
        symfony: [ '5.4', '6.0' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: tests-by-version-${{ matrix.symfony }}-${{ runner.os }}-php${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            tests-by-version-${{ matrix.symfony }}-${{ runner.os }}-php${{ matrix.php }}-composer-

      - name: Setup PHP
        if: success()
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: 'Install project dependencies'
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}.*
        run: |
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer config minimum-stability stable
          composer update --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPUnit
        if: success()
        run: php vendor/bin/phpunit
