name: Validate Composer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    timeout-minutes: 15
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Composer
        id: composer-validate
        if: success()
        run: |
          composer validate

      - name: Prevent Dev Branches
        id: composer-prevent-dev-branches
        if: success()
        run: |
          if [[ `grep "devbbbbb-" composer.json` ]]; then exit 1; fi